=== rikugun/BillingSort/schema/BillSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.example.org/BillSchema" xmlns:tns="http://www.example.org/BillSchema" elementFormDefault="qualified">

    <complexType name="root">
    	<sequence>
    		<element name="call" type="tns:call" maxOccurs="unbounded" minOccurs="0"></element>
    	</sequence>
    </complexType>
    
    <complexType name="call">
    	<sequence>
    		<element name="name" type="string"></element>
    		<element name="telephone" type="integer"></element>
    		<element name="address" type="string"></element>
    		<element name="starttime" type="dateTime"></element>
    		<element name="endtime" type="dateTime"></element>
    		<element name="charge" type="decimal"></element>
    	</sequence>
    </complexType>


    <element name="root" type="tns:root"></element>
</schema>

=== rikugun/BillingSort/billings/billings.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:root xmlns:tns="http://www.example.org/BillSchema"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.example.org/BillSchema schema/BillSchema.xsd ">
	<tns:call>
		<tns:name>rikugun</tns:name>
		<tns:telephone>18677180402</tns:telephone>
		<tns:address>南京</tns:address>
		<tns:starttime>2001-12-31T12:13:07</tns:starttime>
		<tns:endtime>2001-12-31T12:25:10</tns:endtime>
		<tns:charge>12.00</tns:charge>
	</tns:call>
	<tns:call>
		<tns:name>rikugun</tns:name>
		<tns:telephone>18677180402</tns:telephone>
		<tns:address>南京</tns:address>
		<tns:starttime>2001-12-31T12:13:07</tns:starttime>
		<tns:endtime>2001-12-31T12:25:10</tns:endtime>
		<tns:charge>12.00</tns:charge>
	</tns:call>
	<tns:call>
		<tns:name>rikugun</tns:name>
		<tns:telephone>18677180402</tns:telephone>
		<tns:address>南京</tns:address>
		<tns:starttime>2001-12-31T12:13:07</tns:starttime>
		<tns:endtime>2001-12-31T12:25:10</tns:endtime>
		<tns:charge>12.00</tns:charge>
	</tns:call>
	<tns:call>
		<tns:name>rikugun</tns:name>
		<tns:telephone>18677180402</tns:telephone>
		<tns:address>南京</tns:address>
		<tns:starttime>2001-12-31T12:13:07</tns:starttime>
		<tns:endtime>2001-12-31T12:25:10</tns:endtime>
		<tns:charge>12.00</tns:charge>
	</tns:call>
	<tns:call>
		<tns:name>rikugun</tns:name>
		<tns:telephone>18677180402</tns:telephone>
		<tns:address>南京</tns:address>
		<tns:starttime>2001-12-31T12:13:07</tns:starttime>
		<tns:endtime>2001-12-31T12:25:10</tns:endtime>
		<tns:charge>12.00</tns:charge>
	</tns:call>
	<tns:call>
		<tns:name>rikugun</tns:name>
		<tns:telephone>18677180402</tns:telephone>
		<tns:address>南京</tns:address>
		<tns:starttime>2001-12-31T12:13:07</tns:starttime>
		<tns:endtime>2001-12-31T12:25:10</tns:endtime>
		<tns:charge>12.00</tns:charge>
	</tns:call>
	<tns:call>
		<tns:name>rikugun</tns:name>
		<tns:telephone>18677180402</tns:telephone>
		<tns:address>南京</tns:address>
		<tns:starttime>2001-12-31T12:13:07</tns:starttime>
		<tns:endtime>2001-12-31T12:25:10</tns:endtime>
		<tns:charge>12.00</tns:charge>
	</tns:call>
	<tns:call>
		<tns:name>rikugun</tns:name>
		<tns:telephone>18677180402</tns:telephone>
		<tns:address>南京</tns:address>
		<tns:starttime>2001-12-31T12:13:07</tns:starttime>
		<tns:endtime>2001-12-31T12:25:10</tns:endtime>
		<tns:charge>12.00</tns:charge>
	</tns:call>
	<tns:call>
		<tns:name>rikugun</tns:name>
		<tns:telephone>18677180402</tns:telephone>
		<tns:address>南京</tns:address>
		<tns:starttime>2001-12-31T12:13:07</tns:starttime>
		<tns:endtime>2001-12-31T12:25:10</tns:endtime>
		<tns:charge>12.00</tns:charge>
	</tns:call>


</tns:root>
